spring.application.name=quizapp
# application.properties
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# --- コネクション切れ対策 (HikariCP設定) ---
# コネクションの最大寿命を10分(600000ミリ秒)に設定（Supabaseの自動切断より短くする）
spring.datasource.hikari.max-lifetime=600000
# 30秒(30000ミリ秒)ごとに生存確認(Keepalive)を行う
spring.datasource.hikari.keepalive-time=30000